<template>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
  <div><el-button type="primary">主要按钮</el-button></div>
</template>

<script setup>
import { ref } from 'vue'

const value1 = ref(true)
const value2 = ref(true)
</script>

<style lang="scss" scoped></style>
